"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = os.getenv("DBPATH",os.path.join(BASE_DIR, 'templates'))
DBPATH = os.getenv("DBPATH",os.path.join(BASE_DIR, 'db.sqlite3'))
STATIC_ROOT = os.getenv("STATIC_ROOT",os.path.join(os.path.dirname(BASE_DIR),"static_root"))
STATIC_DIR = os.getenv("STATIC_DIR",os.path.join(BASE_DIR,"static"))
SECRET_KEY = os.getenv("SECRET_KEY",'6-%he$yf7+usy*@*%^y57j7+4y@uyg6m_r+z1l7ecv2a2lv0&k')

accept_yes =  ["True", "true", "yes", "y","Yes", "Y"]
accept_no =  ["False","false","no","n","No", "N"]
DEBUG = os.environ.get("DEBUG")
if DEBUG in accept_yes:
    DEBUG = True
elif DEBUG in accept_no:
    DEBUG = False
else:
    print(f"Found DEBUG env variable set to {DEBUG}. Acceptable answers are: {accept_yes} and {accept_no }. Starting with DEBUG=False")
    DEBUG = False
    
ALLOWED_HOSTS_FROM_ENV = os.getenv("ALLOWED_HOSTS","*")
ALLOWED_HOSTS = [ALLOWED_HOSTS_FROM_ENV]

print("*"*80)
print(f"BASE_DIR: {BASE_DIR}")
print(f"DBPATH: {DBPATH}")
print(f"STATIC_ROOT: {STATIC_ROOT}")
print(f"SECRET_KEY: {SECRET_KEY}")
print(f"DEBUG: {DEBUG}")
print(f"TEMPLATES: {TEMPLATES}")
print(f"STATIC_DIR: {STATIC_DIR}")
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print("*"*80)


static_root_path = Path(STATIC_ROOT)

if not static_root_path.exists():
    static_root_path.mkdir()
elif not static_root_path.is_dir():
    print(f"STATIC_ROOT: {STATIC_ROOT} exists as a file. Please delete or point STATIC_ROOT elsewhere")
    sys.exit(1)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DBPATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# St atic files not tied to a particular app.
STATICFILES_DIRS = (
    STATIC_DIR,
)
